<?php
namespace Xmf\Xadr;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-08-12 at 22:36:00.
 */
class ConfigurationAbstractTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var ConfigurationAbstract
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConfigurationAbstract;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
