<?php
/**
* PHPUnit special settings :
* @backupGlobals disabled
* @backupStaticAttributes disabled
*/

namespace Xmf\Xadr;

require_once(dirname(__FILE__).'/../../../init_mini.php');

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-28 at 08:48:30.
 */
class XadrTest extends \MY_UnitTestCase
{
    /**
     * @var Xadr
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Xadr;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testXadr()
    {
        $this->assertNotNull(Xadr::RENDER_CLIENT);
        $this->assertNotNull(Xadr::RENDER_VAR);
        $this->assertNotNull(Xadr::REQUEST_NONE);
        $this->assertNotNull(Xadr::REQUEST_GET);
        $this->assertNotNull(Xadr::REQUEST_POST);
        $this->assertNotNull(Xadr::REQUEST_ALL);
        $this->assertNotNull(Xadr::RESPONSE_ALERT);
        $this->assertNotNull(Xadr::RESPONSE_ERROR);
        $this->assertNotNull(Xadr::RESPONSE_INDEX);
        $this->assertNotNull(Xadr::RESPONSE_INPUT);
        $this->assertNull(Xadr::RESPONSE_NONE);
        $this->assertNotNull(Xadr::RESPONSE_SUCCESS);
    }
}
